# Generated by Django 4.2.28 on 2026-02-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrador'), ('league_admin', 'Administrador de Liga'), ('viewer', 'Espectador')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Semillita, Pre-Infantil, Juvenil', max_length=100, verbose_name='División')),
                ('age_min', models.PositiveSmallIntegerField(verbose_name='Edad mínima')),
                ('age_max', models.PositiveSmallIntegerField(verbose_name='Edad máxima')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la liga')),
                ('country', models.CharField(default='Venezuela', max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_managed', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('bats_hand', models.CharField(choices=[('R', 'Derecho'), ('L', 'Zurdo'), ('S', 'Ambos')], max_length=1, verbose_name='Batea')),
                ('throws_hand', models.CharField(choices=[('R', 'Derecho'), ('L', 'Zurdo')], max_length=1, verbose_name='Lanza')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'players',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Temporada 2025-2026', max_length=100, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(verbose_name='Fin')),
                ('is_active', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.league')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'db_table': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del estadio')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Estadio',
                'verbose_name_plural': 'Estadios',
                'db_table': 'stadiums',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del equipo')),
                ('short_name', models.CharField(help_text='Ej: MAG', max_length=10, verbose_name='Abreviatura')),
                ('logo_url', models.URLField(blank=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, verbose_name='Director técnico')),
                ('won', models.PositiveSmallIntegerField(default=0, verbose_name='Ganados')),
                ('lost', models.PositiveSmallIntegerField(default=0, verbose_name='Perdidos')),
                ('tied', models.PositiveSmallIntegerField(default=0, verbose_name='Empatados')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.category')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.season')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('live', 'En progreso'), ('finished', 'Finalizado'), ('suspended', 'Suspendido'), ('postponed', 'Pospuesto')], default='scheduled', max_length=15)),
                ('home_score', models.PositiveSmallIntegerField(default=0, verbose_name='Carreras local')),
                ('away_score', models.PositiveSmallIntegerField(default=0, verbose_name='Carreras visitante')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='core.team', verbose_name='Equipo visitante')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.category')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.team', verbose_name='Equipo local')),
                ('losing_pitcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses', to='core.player', verbose_name='Pitcher perdedor')),
                ('save_pitcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saves', to='core.player', verbose_name='Pitcher salvado')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.season')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='core.stadium')),
                ('winning_pitcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='core.player', verbose_name='Pitcher ganador')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'db_table': 'games',
                'ordering': ['-game_date'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.league'),
        ),
        migrations.CreateModel(
            name='StatsPitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_outs', models.PositiveSmallIntegerField(default=0, help_text='1.1 IP = 4 outs, 3 IP = 9 outs', verbose_name='Outs lanzados (IP×3)')),
                ('h', models.PositiveSmallIntegerField(default=0, verbose_name='Hits permitidos')),
                ('r', models.PositiveSmallIntegerField(default=0, verbose_name='Carreras totales')),
                ('er', models.PositiveSmallIntegerField(default=0, verbose_name='Carreras limpias (ER)')),
                ('bb', models.PositiveSmallIntegerField(default=0, verbose_name='Boletos (BB)')),
                ('so', models.PositiveSmallIntegerField(default=0, verbose_name='Ponches (SO)')),
                ('hr', models.PositiveSmallIntegerField(default=0, verbose_name='Jonrones permitidos (HR)')),
                ('wp', models.PositiveSmallIntegerField(default=0, verbose_name='Wild Pitch (WP)')),
                ('bk', models.PositiveSmallIntegerField(default=0, verbose_name='Balks (BK)')),
                ('hbp', models.PositiveSmallIntegerField(default=0, verbose_name='Golpeados (HBP)')),
                ('decision', models.CharField(blank=True, choices=[('win', 'Victoria (W)'), ('loss', 'Derrota (L)'), ('save', 'Salvado (S)'), ('hold', 'Hold (H)')], max_length=4, null=True, verbose_name='Decisión del juego')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_stats', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_stats', to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_stats', to='core.team')),
            ],
            options={
                'verbose_name': 'Estadística de pitcheo',
                'verbose_name_plural': 'Estadísticas de pitcheo',
                'db_table': 'stats_pitching',
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.CreateModel(
            name='StatsBatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa', models.PositiveSmallIntegerField(default=0, verbose_name='Apariciones al plato (PA)')),
                ('ab', models.PositiveSmallIntegerField(default=0, verbose_name='Turnos al bate (AB)')),
                ('r', models.PositiveSmallIntegerField(default=0, verbose_name='Carreras (R)')),
                ('h', models.PositiveSmallIntegerField(default=0, verbose_name='Hits (H)')),
                ('doubles', models.PositiveSmallIntegerField(default=0, verbose_name='Dobles (2B)')),
                ('triples', models.PositiveSmallIntegerField(default=0, verbose_name='Triples (3B)')),
                ('hr', models.PositiveSmallIntegerField(default=0, verbose_name='Jonrones (HR)')),
                ('rbi', models.PositiveSmallIntegerField(default=0, verbose_name='Carreras impulsadas (RBI)')),
                ('bb', models.PositiveSmallIntegerField(default=0, verbose_name='Bases por bolas (BB)')),
                ('so', models.PositiveSmallIntegerField(default=0, verbose_name='Ponches (SO/K)')),
                ('sb', models.PositiveSmallIntegerField(default=0, verbose_name='Bases robadas (SB)')),
                ('cs', models.PositiveSmallIntegerField(default=0, verbose_name='Capturado en robo (CS)')),
                ('hbp', models.PositiveSmallIntegerField(default=0, verbose_name='Golpeado por lanzador (HBP)')),
                ('sf', models.PositiveSmallIntegerField(default=0, verbose_name='Sacrificios fly (SF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='core.team')),
            ],
            options={
                'verbose_name': 'Estadística de bateo',
                'verbose_name_plural': 'Estadísticas de bateo',
                'db_table': 'stats_batting',
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveSmallIntegerField(verbose_name='Número de dorsal')),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera base'), ('2B', 'Segunda base'), ('3B', 'Tercera base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter'), ('UT', 'Utility')], max_length=2, verbose_name='Posición')),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='core.team')),
            ],
            options={
                'verbose_name': 'Roster',
                'verbose_name_plural': 'Rosters',
                'db_table': 'rosters',
                'unique_together': {('team', 'player')},
            },
        ),
    ]
