# Generated by Django 4.2.28 on 2026-03-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsbatting',
            name='ibb',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Boletos intencionales (IBB/I)'),
        ),
        migrations.AddField(
            model_name='statsbatting',
            name='sh',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sacrificios hit/toque (SH)'),
        ),
    ]
