# Generated by Django 4.2.28 on 2026-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statsbatting_ibb_statsbatting_sh'),
    ]

    operations = [
        migrations.AddField(
            model_name='statspitching',
            name='ab_against',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Veces al bate (VB)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='complete_game',
            field=models.BooleanField(default=False, verbose_name='Juego Completo (C)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='h2_allowed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dobles (H2)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='h3_allowed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Triples (H3)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='is_reliever',
            field=models.BooleanField(default=False, verbose_name='Relevista (R)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='is_starter',
            field=models.BooleanField(default=False, verbose_name='Abridor (I)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='loss',
            field=models.BooleanField(default=False, verbose_name='Perdido (P)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='pitch_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Lanzamientos (LZ)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='save',
            field=models.BooleanField(default=False, verbose_name='Salvado (S)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='sf_allowed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sacrificios fly (SF)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='sh_allowed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sacrificios toque (SH)'),
        ),
        migrations.AddField(
            model_name='statspitching',
            name='win',
            field=models.BooleanField(default=False, verbose_name='Ganado (G)'),
        ),
        migrations.AlterField(
            model_name='statspitching',
            name='decision',
            field=models.CharField(blank=True, choices=[('win', 'Victoria (W)'), ('loss', 'Derrota (L)'), ('save', 'Salvado (S)'), ('hold', 'Hold (H)')], max_length=4, null=True, verbose_name='Decisión (Legacy)'),
        ),
        migrations.AlterField(
            model_name='statspitching',
            name='er',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Carreras limpias (CL)'),
        ),
        migrations.AlterField(
            model_name='statspitching',
            name='h',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Hits (HP)'),
        ),
        migrations.AlterField(
            model_name='statspitching',
            name='hbp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Golpeados (GP)'),
        ),
        migrations.AlterField(
            model_name='statspitching',
            name='hr',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Jonrones (HR)'),
        ),
        migrations.AlterField(
            model_name='statspitching',
            name='ip_outs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Outs lanzados (IP×3)'),
        ),
        migrations.AlterField(
            model_name='statspitching',
            name='r',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Carreras (CP)'),
        ),
        migrations.AlterField(
            model_name='statspitching',
            name='so',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ponches (K)'),
        ),
    ]
