# Generated by Django 4.2.28 on 2026-03-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statspitching_ab_against_statspitching_complete_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='position',
        ),
        migrations.AddField(
            model_name='statsbatting',
            name='position',
            field=models.CharField(blank=True, choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera base'), ('2B', 'Segunda base'), ('3B', 'Tercera base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designado'), ('PH', 'Pinch Hitter'), ('PR', 'Pinch Runner'), ('UT', 'Utility')], max_length=2, null=True, verbose_name='Posición jugada'),
        ),
    ]
