# Generated by Django 4.2.28 on 2026-03-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_roster_position_statsbatting_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_upload',
            field=models.ImageField(blank=True, help_text='Sube una imagen. Se optimizará y guardará automáticamente en Supabase.', null=True, upload_to='tmp/', verbose_name='Foto del pelotero'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo_upload',
            field=models.ImageField(blank=True, help_text='Sube una imagen. Se optimizará y guardará automáticamente en Supabase.', null=True, upload_to='tmp/', verbose_name='Logo del equipo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL de foto (auto)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL del logo (auto)'),
        ),
    ]
